steps:
- id: "Pull Templates"
  name: 'gcr.io/$PROJECT_ID/faas-cli:0.12.5'
  args: ['faas-cli', 'template', 'pull', 'https://github.com/flexibility-org/python-flask-template']

- id: "Do a shrinkwrap build"
  name: 'gcr.io/$PROJECT_ID/faas-cli:0.12.5'
  args: ['faas-cli', 'build', '-f', './hello.yml', '--shrinkwrap']

- id: "Build the docker image"
  name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t=gcr.io/$PROJECT_ID/hello:$SHORT_SHA', '-t=gcr.io/$PROJECT_ID/hello:latest', '-f', './build/hello/Dockerfile', './build/hello/']

- id: "Push docker image"
  name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/hello:latest']

- id: "Login with faas-cli login & Deploy to my RPi Cluster"
  name: "gcr.io/$PROJECT_ID/faas-cli:0.12.4"
  args:
  - 'echo'
  - '$$OPENFAAS_PASSWD'
  - '|'
  - 'faas-cli'
  - 'login'
  - '--password-stdin'
  - '-g'
  - '${_GATEWAY}'
  - '&&'
  - 'faas-cli'
  - 'deploy'
  - '-f'
  - './hello.yml'
  - '-g'
  - '${_GATEWAY}'
  secretEnv: ['OPENFAAS_PASSWD']

options:
  volumes:
    - name: 'buildvol'
      path: '/openfaas'

substitutions:
  _GATEWAY: http://35.192.130.206:8080
  
secrets:
- kmsKeyName: "projects/uts-1382/locations/global/keyRings/openfaas/cryptoKeys/gke-openfaas-gw"
  secretEnv:
    OPENFAAS_PASSWD: "CiQAWlwxhlIkVVnXIvbIxrJkQstg6Z9N6UfJWNs5aFGKs8isvKgSNQCxF0+Ci8atE53ztsUXshS5XrEHw/wJFGOqKMntx0eq5XV1jgHBUli9VGeIHZo/07Nytyj8"
